import { StyleSheet } from 'react-native';
import fonts from 'assets/fonts';

const styles = (colors: any) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: '#FAFAFA',
    },
    navBar: {
      backgroundColor: colors.white,

      height: 50,
      width: '100%',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.24,
      shadowRadius: 4,
      elevation: 2,
      flexDirection: 'row',
      paddingLeft: 20,
      alignItems: 'center',
    },
    navHeading: {
      fontFamily: fonts.bold,
      fontSize: 18,
      color: '#054E8B',
      paddingLeft: 21,
      paddingTop: 10,
      paddingBottom: 10,
    },
    container2: {
      paddingTop: 20,
      paddingLeft: 20,
      paddingRight: 20,
      flexDirection: 'column',
    },
    text: { color: '#8493AE', fontSize: 15, fontWeight: '700' },
    box: {
      marginTop: 10,
      height: 46,
      backgroundColor: colors.white,
      width: '100%',
      shadowOffset: {
        width: 0,
        height: 0,
      },
      shadowOpacity: 0.24,
      shadowRadius: 4,
      elevation: 2,
      flexDirection: 'row',

      alignItems: 'center',
      borderRadius: 8,
      paddingLeft: 10,
    },
    centeredView: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      marginTop: 22,
    },
    modalView: {
      margin: 20,
      backgroundColor: 'white',
      borderRadius: 8,
      paddingTop: 24,
      paddingRight: 12,
      paddingBottom: 20,
      paddingLeft: 12,

      alignItems: 'center',
      shadowColor: '#000',
      shadowOffset: {
        width: 0,
        height: 2,
      },
      shadowOpacity: 0.25,
      shadowRadius: 4,
      elevation: 5,
    },
    image: {
      width: 30,
      height: 30,
    },
    noDeviceHeader: {
      marginTop: 15,
      color: '#054E8B',
      fontSize: 19,
      fontWeight: '700',
      textAlign: 'center',
      lineHeight: 25,
    },
    noDeviceContent: {
      marginTop: 15,
      color: '#2A3752',
      fontSize: 15,
      fontWeight: '400',
      textAlign: 'center',
      lineHeight: 19,
    },
    buttonContainer: {
      marginTop: 'auto',
      alignSelf: 'center',
      backgroundColor: '#1B96D8',
      justifyContent: 'center',
      height: 40,
      width: 320,
      borderRadius: 8,
    },
    buttonContent: {
      color: 'white',
      fontSize: 19,
      fontWeight: '700',
      textAlign: 'center',
    },
    modalHeader: {
      fontSize: 17,
      fontWeight: '700',
      color: '#054E8B',
      textAlign: 'center',
      lineHeight: 22,
    },
    modalContent: {
      marginTop: 5,
      marginBottom: 5,
      fontSize: 16,
      fontWeight: '400',
      color: '#455066',
      textAlign: 'center',
      lineHeight: 19,
    },
    unlinkContainer: {
      marginTop: 10,
      height: 40,
      width: 327,
      borderRadius: 8,
      borderColor: '#EA4C59',
      borderWidth: 2,
      justifyContent: 'center',
    },
    unlinkContent: {
      fontSize: 19,
      fontWeight: '700',
      color: '#2A3752',
      textAlign: 'center',
      lineHeight: 25,
    },
    unlinkClose: {
      marginTop: 10,
      fontSize: 17,
      fontWeight: '400',
      color: '#8493AE',
      textAlign: 'center',
      lineHeight: 21,
    },
    unlinkSuccess: {
      marginTop: 20,
      fontSize: 19,
      fontWeight: '700',
      color: '#054E8B',
      textAlign: 'center',
      lineHeight: 25,
    },
    relink: {
      marginTop: 10,
      marginBottom: 10,
      fontSize: 15,
      fontWeight: '400',
      color: '#2A3752',
      textAlign: 'center',
      lineHeight: 19,
    },
    unlinkConfirm: {
      marginTop: 10,
      height: 40,
      width: 327,
      borderRadius: 8,
      backgroundColor: '#1B96D8',
      justifyContent: 'center',
    },
    unlinkConfirmed: {
      fontSize: 19,
      fontWeight: '700',
      color: '#FFFFFF',
      textAlign: 'center',
      lineHeight: 25,
    },
  });
export default styles;
