export const HEALTH_TRACKER = '[HEALTH] HEALTH_TRACKER';
export const GET_DASHBOARD = '[DASHBOARD] GET_DASHBOARD';
export const MEDICAL_DROPDOWN = '[MEDICATION] MEDICAL_DROPDOWN';
export const GET_HEALTH_RISK = '[HEALTH] GET_HEALTH_RISK';
