export const HEALTH_TRACKER = '[HEALTH] HEALTH_TRACKER';
export const GET_DASHBOARD = '[DASHBOARD] GET_DASHBOARD';
export const MEDICAL_DROPDOWN = '[MEDICATION] MEDICAL_DROPDOWN';
export const MEDICATION_LIST = '[MEDICATION] MEDICATION_LIST';
export const GET_HEALTH_RISK = '[HEALTH] GET_HEALTH_RISK';
export const GET_NEW_MEDICATION_TRACKER = '[HEALTH] GET_NEW_MEDICATION_TRACKER';
export const PSP_MODULE = '[PSP] PSP_MODULE';
export const PSP_HYPER_MODULE = '[PSP] PSP_HYPER_MODULE';
export const PSP_PDF_LINK = '[PDF] PSP_PDF_LINK';
export const GET_LAB_STATUS = '[LAB] GET_LAB_STATUS';
export const GET_RESULT_OVERVIEW = '[HEALTH] GET_RESULT_OVERVIEW';
export const GET_LATEST_RESULT = '[RESULT] GET_LATEST_RESULT';
export const GET_PAST_RESULT = '[PAST] GET_PAST_RESULT';
export const GET_PSP_HYPERTENSION_HEALTH_TRACKER =
  '[HEALTH TRACKER] GET_PSP_HYPERTENSION_HEALTH_TRACKER';
export const PSP_PDF_HYPER_LINK = '[PSP HYPER] PSP_PDF_HYPER_LINK';
