platform :ios, '12.0'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native/scripts/react_native_pods'

#source 'https://github.com/CocoaPods/Specs.git'

def pods()
  # Pods for RnDiffApp
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  use_frameworks!
end

target "BioMark" do
    pods()
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'react-native-pdf', :path => '../node_modules/react-native-pdf'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera"

end

dynamic_frameworks = ['Socket.IO-Client-Swift', 'Starscream', 'iProov']

# make all the other frameworks into static frameworks by overriding the static_framework? function to return true
pre_install do |installer|
  installer.pod_targets.each do |pod|
    if !dynamic_frameworks.include?(pod.name)
      puts "Overriding the static_framework? method for #{pod.name}"
      def pod.static_framework?;
        true
      end
      def pod.build_type;
        Pod::BuildType.static_library
      end
    end
  end
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  target 'BioMarkTests' do
    inherit! :complete
    # Pods for testing
  end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
end
